### ISSUE TITLE
Exception after closing Run/Debug Configurations

### ISSUE THREAD

**Issue by bazzik** [3mmarg97/LaravelStorm#2]
PhpStorm 2017.1.4 on Windows 10 using bundled x64 JDK; LaravelStorm Version: 1.0 (installed just few mins ago)

```
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

1. "Run | Edit Configurations"
2. Click on "+" to create new configuration of "Laravel" type
3. No need to do anything -- just close the window by clicking on "Cancel" button
4. Exception below will happen

**P.S.** List of plugins (in case if your is conflicting with one of them)

- **Loaded bundled plugins:** ASP (0.1), Apache config (.htaccess) support (171.4694.2), Blade Support (171.4694.2), CSS Support (171.4694.2), Command Line Tool Support (171.4694.2), Database Tools and SQL (1.0), Docker integration (2.5.3.1), File Watchers (171.4694.2), GNU GetText files support (*.po) (171.4694.2), Gherkin (999.999), Git Integration (8.1), GitHub (171.4694.2), HTML Tools (2.0), IDEA CORE (171.4694.2), Ini4Idea (171.4694.2), IntelliLang (8.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), Less support (171.4694.2), Markdown support (VERSION), NodeJS (171.4694.2), PHP (171.4694.2), PHP Docker (171.4694.2), PHP Remote Interpreter (171.4694.2), Performance Testing (171.4694.2), Phing Support (171.4694.2), QuirksMode (171.4694.2), REST Client (171.4694.2), ReStructuredText Support (171.4694.2), Refactor-X (2.01), Remote Hosts Access (0.1), SSH Remote Run (0.1), Sass support (171.4694.2), Task Management (1.0), Terminal (0.1), TextMate bundles support (VERSION), Twig Support (171.4694.2), UML Support (1.0), Vagrant (171.4694.2), W3C Validators (2.0), WordPress Support (171.4694.2), XPathView + XSLT Support (4), YAML (171.4694.2), hg4idea (10.0), tslint (171.4694.2) 
- **Loaded custom plugins:** .env files support (0.3), BrowseWordAtCaret (3.0.4), CamelCase (2.0.0), EditorConfig (171.2613.14), FavoriteFolders (1.2.0.1), Frame Switcher (3.7.0-162), Grep Console (6.6.163.000.0), Laravel Insight (0.3.0), Laravel Plugin (0.14.2), LaravelStorm (1.0), PHP Advanced AutoComplete (1.0.4), PHP Annotations (5.0), Php Inspections (EA Extended) (2.3.8-preview.1), PostCSS support (171.3566.29), Refactoring (0.0.5), Shifter (1.7.3), String Manipulation (5.4.143.000.0), Tabdir (1.6.6), Zero Width Characters locator (0.93) 
- **Disabled plugins:** AngularJS (171.4694.2), Behat Support (171.4694.2), CVS Integration (11), Codeception Framework (171.4694.2), CoffeeScript (2.0), Copyright (8.1), Drupal Support (171.4694.2), Google App Engine Support for PHP (171.4694.2), Haml (171.4694.2), Joomla! Support (171.4694.2), Options completion plugin (0.0.7), PHP Class Templates (1.0.2), PHPSpec BDD Framework (171.4694.2), Perforce Integration (2.0), PhpStorm Workshop (171.4694.2), Referencer (1.2.0), Settings Repository (171.4694.2), Stylus support (171.4424.63), Subversion Integration (1.1), Symfony Plugin (0.14.147), Time Tracking (1.0), XSLT-Debugger (1.4) 

```
null
java.lang.NullPointerException
	at com.smartbit8.laravelstorm.ui.LaravelRunConfSettingsEditor.resetEditorFrom(LaravelRunConfSettingsEditor.java:41)
	at com.smartbit8.laravelstorm.ui.LaravelRunConfSettingsEditor.resetEditorFrom(LaravelRunConfSettingsEditor.java:21)
	at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:86)
	at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:93)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:86)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:307)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:291)
	at com.intellij.openapi.options.CompositeSettingsEditor.resetEditorFrom(CompositeSettingsEditor.java:51)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:109)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:44)
	at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:86)
	at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:93)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:86)
	at com.intellij.openapi.options.SettingsEditorConfigurable.reset(SettingsEditorConfigurable.java:50)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.reset(SingleConfigurationConfigurable.java:138)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:99)
	at com.intellij.execution.impl.RunConfigurable.a(RunConfigurable.java:1070)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.java:1103)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction.a(RunConfigurable.java:1133)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:82)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:48)
	at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:403)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:355)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:510)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:574)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:735)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:457)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:968)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:958)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:952)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1396)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ammardev** [comment]
Problem Solved in the code . So please download version 0.9 or wait  for 1.1 . The new Version need about 2 days to be uploaded to the Jetbrains repositories . Thanks for reporting the problem
